main	identificateur	main
(	symbole	PARENTHESE_OUVRANTE
)	symbole	PARENTHESE_FERMANTE
{	symbole	ACCOLADE_OUVRANTE
a	identificateur	a
+	symbole	PLUS
a	identificateur	a
;	symbole	POINT_VIRGULE
}	symbole	ACCOLADE_FERMANTE
